#!/bin/bash
#
#	Start the mysql database
#
bin=`dirname $0`
. $bin/env.sh


imagename=${CONTAINER_NAME}-image:latest

#
#	Remove any old or running container
#
echo ''
echo '** Remove any old container.'
echo "$" docker stop ${CONTAINER_NAME}
         docker stop ${CONTAINER_NAME}
echo "$" docker rm ${CONTAINER_NAME}
         docker rm ${CONTAINER_NAME}
echo ''

#
#	Start the Docker container
#
echo '** Start a new container using the new image.'
echo "$" docker run --name ${CONTAINER_NAME} -p ${SSH_PORT}:22 -p ${HTTP_PORT}:80 -p ${DB_PORT}:3306 -d ${imagename}
         docker run --name ${CONTAINER_NAME} -p ${SSH_PORT}:22 -p ${HTTP_PORT}:80 -p ${DB_PORT}:3306 -d ${imagename}
#		-v /etc/localtime:/etc/localtime:ro \



if [ $? == 0 ] ; then

	# Successful start
	echo ""
	echo ""
	echo "        Host: ${DOCKER_IP}"
	echo "        Port: ${DB_PORT}"
	echo ""
	echo "        phpMyAdmin: http://${DOCKER_IP}:${HTTP_PORT}/phpmyadmin"
	echo ""
	exit 0
else
	# Error return
	echo ""
	echo ""
	echo "Error: starting the database container failed."
	echo ""
	exit 1;
fi
