#!/bin/bash
#
#	Run SOLR in a Docker container
#
dir=`dirname $0`
. ${dir}/../env.sh

CONTAINER_NAME=${PROJECT}-solr

#
#	Remove any old or running container
#
echo ''
echo '** Remove any old container.'
echo "$" docker stop ${CONTAINER_NAME}
         docker stop ${CONTAINER_NAME}
echo "$" docker rm ${CONTAINER_NAME}
         docker rm ${CONTAINER_NAME}
echo ''

echo "$" docker run --name ${CONTAINER_NAME} -it -d -p 8983:8983 -t makuk66/docker-solr
docker run --name ${CONTAINER_NAME} -it -d -p 8983:8983 -t makuk66/docker-solr
