#!/bin/bash
#
#	Start a REDIS server in Docker
#
dir=`dirname $0`
. ${dir}/../env.sh

CONTAINER_NAME=${PROJECT}-redis

#
#	Remove any old or running container
#
echo ''
echo '** Remove any old container.'
echo "$" docker stop ${CONTAINER_NAME}
         docker stop ${CONTAINER_NAME}
echo "$" docker rm ${CONTAINER_NAME}
         docker rm ${CONTAINER_NAME}
echo ''

echo "$" docker run --name ${CONTAINER_NAME} -d -p 6379:6379 redis
docker run --name ${CONTAINER_NAME} -d -p 6379:6379 redis
