#!/bin/sh
#
#	Start Selenium in a Docker container
#
dir=`dirname $0`
. ${dir}/../env.sh
CONTAINER_NAME=${PROJECT}-redis

#
#	Stop the container
#
echo docker stop ${CONTAINER_NAME}
docker stop ${CONTAINER_NAME}

#
#	Remove the container
#
echo docker rm ${CONTAINER_NAME}
docker rm ${CONTAINER_NAME}
