#!/bin/sh
#
#	Start Selenium in a Docker container
#
dir=`dirname $0`
. ${dir}/../env.sh

CONTAINER_NAME=${PROJECT}-selenium

#
#	Remove any old or running container
#
echo ''
echo '** Remove any old container.'
echo "$" docker stop ${CONTAINER_NAME}
         docker stop ${CONTAINER_NAME}
echo "$" docker rm ${CONTAINER_NAME}
         docker rm ${CONTAINER_NAME}
echo ''

#sudo docker run --rm --name ${CONTAINER_NAME} --privileged -p 4444:4444 -p 5900:5900 elgalu/docker-selenium
echo "$" docker run --name ${CONTAINER_NAME} -d --privileged -p 4444:4444 -p 5900:5900 elgalu/docker-selenium
docker run --name ${CONTAINER_NAME} -d --privileged -p 4444:4444 -p 5900:5900 elgalu/docker-selenium
